name: setup

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 9.12.1

    - uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ matrix.node-version }}

    - run: pnpm install
      shell: bash
