name: status

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - run: yarn --frozen-lockfile
        shell: bash

      - run: yarn build
        shell: bash

  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - run: yarn --frozen-lockfile
        shell: bash

      - run: yarn chore:lint
        shell: bash

  test:
    name: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - run: yarn --frozen-lockfile
        shell: bash

      - run: yarn test
        shell: bash

  typecheck:
    name: typecheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - run: yarn --frozen-lockfile
        shell: bash

      - run: yarn test:typecheck
        shell: bash
