name: status

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm i --frozen-lockfile=false
        shell: bash

      - run: pnpm build
        shell: bash

  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm i --frozen-lockfile=false
        shell: bash

      - run: pnpm lint
        shell: bash

  typecheck:
    name: typecheck

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: actions/setup-node@master
        with:
          node-version: 16.x

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: pnpm i --frozen-lockfile=false
        shell: bash

      - run: pnpm typecheck
        shell: bash
